item {
    id: 1
    name: 'Car'
}
item {
    id: 2
    name: 'Bus'
}
item {
    id: 3
    name: 'Truck'
}
item {
    id: 4
    name: 'Van'
}
item {
    id: 5
    name: 'Motorcycle'
}
item {
    id: 6
    name: 'Vehicle'
}